kind: Deployment
apiVersion: apps/v1
metadata:
   name: pijey
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pijey
   template:
      metadata:
        labels:
          app: pijey
      spec:
       containers:
        - name: pijey
          image: pijey03/k8s-test
          imagePullPolicy: Always
          ports:
          - containerPort: 80
