kind: Deployment
apiVersion: apps/v1
metadata:
   name: kloudinsight
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: kloudinsight
   template:
      metadata:
        labels:
          app: kloudinsight
      spec:
       containers:
        - name: kloudinsight
          image: kloudinsight/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
