kind: Service                             
apiVersion: v1
metadata:
  name: kloudinsight
  labels:
    app: kloudinsight
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kloudinsight                    
  type: LoadBalancer                   
